<?php

require_once 'vendor/autoload.php';
require_once 'config/constants.php';



try {
// Create the Transport
$transport = (new Swift_SmtpTransport('smtp.googlemail.com', 465, 'ssl'))
  ->setUsername(EMAIL)
  ->setPassword(PASSWORD);

// Create the Mailer using your created Transport
$mailer = new Swift_Mailer($transport);



function sendVerificationEmail($userEmail, $token) 
{
	global $mailer;

	$body = '<!DOCTYPE html>
<html>
<head>
	<title>Verify email</title>
</head>
<body>
	<div class="wrapper">
		<p>
			Thank you for signing up on our website. Please click on the link below to verify your email.
		</p>
		<a href="http://localhost/iamacityofnagascholar/schlradminlogin.php?token='. $token .'">
			Verify your email address
		</a>
		<p><i><small>Do not reply to this email. This is autogenerated.</small></i></p>
	</div>
</body>
</html>';

	// Create a message
	$message = (new Swift_Message('Verify your email address'))
	  ->setFrom(EMAIL)
	  ->setTo($userEmail)
	  ->setBody($body, 'text/html');

	// Send the message
	$result = $mailer->send($message);
}

function sendPasswordResetLink($userEmail, $url) 
{
	global $mailer;

	$body = '<!DOCTYPE html>
<html>
<head>
	<title>Verify email</title>
</head>
<body>
	<div class="wrapper">
		<p>	
			Hello. Please click on the link below to reset your password.
		</p>
		<a href="'. $url .'">Change Password
		</a>
		<p><i><small>Do not reply to this email. This is autogenerated.</small></i></p>
	</div>
</body>
</html>';

	// Create a message
	$message = (new Swift_Message('Reset your Password'))
	  ->setFrom(EMAIL)
	  ->setTo($userEmail)
	  ->setBody($body, 'text/html');

	// Send the message
	$result = $mailer->send($message);
}


function sendRequestEmail($applicantEmail, $firstName, $lastName, $messages, $token, $request) 
{
	global $mailer;

	$output = "";
	$subject = "";
	$p1 = "";
	if (!empty($request)) {
		$subject = "Upload Required Documents";
		$N = count($request);
		for($i=0; $i < $N; $i++){
			$output .= '
				<li>'.$request[$i].'</li>';
		}
		$p1 = '<p>Please upload the following requirements to the link below:</p>
			   <u>'. $output .'</u>
			   <a href="http://localhost/iamacityofnagascholar/required_attachments.php?token='. $token .'">
				Upload Required Documents
			   </a><br>
			   <a href="http://localhost/iamacityofnagascholar/#requirements">
				See requirements guide here for reference...
			   </a>';
	} else {
		$subject = "Message";
	}

	$body = '<!DOCTYPE html>
<html>
<head>
	<title>Verify email</title>
</head>
<body>
	<div class="wrapper">
		<p>
			Hello <strong>'. $firstName .' '. $lastName .'</strong>! Good day.
		</p>
		<p>'. $messages .'</p>
		'. $p1 .'
		<p><i><small>Do not reply to this email. This is autogenerated.</small></i></p>
	</div>
</body>
</html>';

	// Create a message
	$message = (new Swift_Message($subject))
	  ->setFrom(EMAIL)
	  ->setTo($applicantEmail)
	  ->setBody($body, 'text/html');

	// Send the message
	$result = $mailer->send($message);
}

function sendExamEmail($applicantEmail, $firstName, $lastName, $token, $examID, $exam) 
{
	global $mailer;

	$body = '<!DOCTYPE html>
<html>
<head>
	<title>Verify email</title>
</head>
<body>
	<div class="wrapper">
		<p>
			Hello <strong>'. $firstName .' '. $lastName .'</strong>! Good day.
		</p>
		<p>Thank you for completing the needed requirements for your scholarship application.</p>
		<p>You can now proceed to take the exam. Click the link below.</p>
		<h1><a href="http://localhost/iamacityofnagascholar/online_exam.php?exam='. $examID .'&token='. $token .'">'.$exam.'</a></h1>
		<p><i><small>Do not reply to this email. This is autogenerated.</small></i></p>
	</div>
</body>
</html>';

	// Create a message
	$message = (new Swift_Message('ICoNS Examination'))
	  ->setFrom(EMAIL)
	  ->setTo($applicantEmail)
	  ->setBody($body, 'text/html');

	// Send the message
	$result = $mailer->send($message);
}

function sendConfirmationEmail($applicantEmail, $firstName, $lastName, $token, $scholarID) 
{
	global $mailer;

	$body = '<!DOCTYPE html>
<html>
<head>
	<title>ICoNS Confirmation</title>
</head>
<body>
	<div class="wrapper">
		<p>
			Hello <strong>'. $firstName .' '. $lastName .'</strong>! Good day.
		</p>
		<p>Congratulations! You can now say that <b>I am a City of Naga Scholar</b>.</p>
		<p>Good luck on your journey.</p>
		<p>Click the link below to create your login credentials.</p>
		<h1><a href="http://localhost/iamacityofnagascholar/signup.php?scholar='. $scholarID .'&token='. $token .'">Sign-up</a></h1>
		<p><i><small>Do not reply to this email. This is autogenerated.</small></i></p>
	</div>
</body>
</html>';

  // Create a message
	$message = (new Swift_Message('ICoNS Confirmation'))
	  ->setFrom(EMAIL)
	  ->setTo($applicantEmail)
	  ->setBody($body, 'text/html');

	// Send the message
	$result = $mailer->send($message);
	
}

} catch(Exception $e) {
    echo $e->getMessage();
}
